"""
Scrutin FastAPI HTTP Server
===========================
Wraps the existing `run_orchestrator` coroutine with a REST API.

Routes:
    GET  /api/healthz         → health check
    POST /api/verify          → run full multi-agent verification pipeline
    GET  /api/docs            → Swagger UI (auto-generated by FastAPI)
    GET  /api/openapi.json    → OpenAPI schema

Start:
    python -m app.server               # starts on port 8000 (default)
    PORT=9000 python -m app.server     # custom port
"""

from __future__ import annotations

import os
from contextlib import asynccontextmanager
from typing import Optional

from fastapi import FastAPI, HTTPException, status
from fastapi.middleware.cors import CORSMiddleware
from pydantic import BaseModel

# ── Startup / Shutdown ────────────────────────────────────────────────────────


@asynccontextmanager
async def lifespan(app: FastAPI):
    """Application lifespan: load .env, run DB migrations, register tools."""
    from dotenv import load_dotenv

    load_dotenv()

    # Run SQLite migrations so the DB schema is always up to date
    db_path = os.getenv("SCRUTIN_DB_PATH", "scrutin.db")
    from app.memory.migrations import run_migrations

    run_migrations(db_path)

    # Register all tools (side-effectful import)
    import app.tools._register_all  # noqa: F401

    # Configure structured logging
    from app.utils.logger import configure_terminal_logger

    configure_terminal_logger(trace=False)

    yield  # application runs here


# ── App ───────────────────────────────────────────────────────────────────────

app = FastAPI(
    title="Scrutin",
    description=(
        "Multi-agent misinformation verification platform. "
        "Submit a text claim or article URL for deep fact-checking."
    ),
    version="0.1.0",
    docs_url="/api/docs",
    openapi_url="/api/openapi.json",
    lifespan=lifespan,
)

# CORS — allow the Vite dev server (any localhost port) and production origin
_allowed_origins = os.getenv(
    "CORS_ORIGINS",
    "http://localhost:5173,http://localhost:3000,http://127.0.0.1:5173",
).split(",")

app.add_middleware(
    CORSMiddleware,
    allow_origins=[o.strip() for o in _allowed_origins],
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)


# ── Request / Response Schemas ────────────────────────────────────────────────


class VerifyRequest(BaseModel):
    """Body for POST /api/verify"""

    claim: Optional[str] = None
    url: Optional[str] = None

    model_config = {"json_schema_extra": {"example": {"claim": "The Eiffel Tower was built in 1889"}}}


class HealthStatus(BaseModel):
    status: str


# ── Routes ────────────────────────────────────────────────────────────────────


@app.get(
    "/api/healthz",
    response_model=HealthStatus,
    summary="Health check",
    tags=["health"],
)
async def healthz() -> HealthStatus:
    """Returns server health status."""
    return HealthStatus(status="ok")


@app.post(
    "/api/verify",
    summary="Verify a claim or article URL",
    tags=["verification"],
    status_code=status.HTTP_200_OK,
)
async def verify(body: VerifyRequest):
    """
    Run the full Scrutin multi-agent verification pipeline.

    Provide **either** `claim` (plain text assertion) or `url` (article URL).
    Returns a `VerificationReport` JSON object.

    Processing typically takes 5–30 seconds depending on claim complexity.
    """
    if not body.claim and not body.url:
        raise HTTPException(
            status_code=status.HTTP_422_UNPROCESSABLE_ENTITY,
            detail="Provide either 'claim' or 'url' in the request body.",
        )

    from app.utils.env_validator import validate_env

    config = validate_env()
    db_path = os.getenv("SCRUTIN_DB_PATH", "scrutin.db")

    raw_input = body.claim or body.url
    input_type = "text" if body.claim else "url"

    # Delegate to the existing orchestrator — zero changes to existing logic
    from app.orchestrator.loop import run_orchestrator

    try:
        report = await run_orchestrator(
            raw_input=raw_input,
            input_type=input_type,
            config=config,
            db_path=db_path,
        )
    except Exception as exc:
        raise HTTPException(
            status_code=status.HTTP_500_INTERNAL_SERVER_ERROR,
            detail=f"Orchestrator error: {str(exc)}",
        ) from exc

    # FastAPI will serialize the Pydantic model automatically
    return report
